### ISSUE TITLE
spaceline-all-the-icons-separators-type not working

### ISSUE THREAD

**Issue by haelmchen** [ekaschalk/dotspacemacs#1]
Hi, 

Since spaceline-all-the-icons messed up my spaceline big time, I finally found the error that was causing the problem.

`spaceline-all-the-icons-separators-type 'arrow`

should be called

`spaceline-all-the-icons-separator-type 'arrow`

The **s** at the end of _separator_ was too much. Now my separators are actually arrows.

**Comment by ekaschalk** [comment]
Nice catch, that fixes those small tint issues in the inactive modeline that can be seen in the images.
