### ISSUE TITLE
How can I add additional package?

### ISSUE THREAD

**Issue by yubrshen** [ekaschalk/dotspacemacs#11]
This is not related to a bug. But a request for help. 

I really enjoy using your .spacemacs.d 

Now, I want to add a package that I used to put by the following code:
`dotspacemacs-additional-packages
   '(pandoc-mode
     interleave
     cdlatex
     org-brain
     realgud
     realgud-pry
     realgud-byebug)
`
I wonder how I can add them in your system? 

I tried to add one to layers/config/packages.el:

`(setq config-packages
      '(
        ;; Owned packages
        outshine

        ;; Elsewhere-owned packages with trivial config
        ispell
        projectile
        yasnippet
        cdlatex ; try to add

        ;; Elsehwere-owned packages
        (avy-config      :location local)
        (eshell-config   :location local)
        (evil-config     :location local)
        (gnus-config     :location local)
        (ivy-config      :location local)
        (org-config      :location local)
        (treemacs-config :location local)
        ))`
But I got the error:
(Spacemacs) Warning: package cdlatex not initialized in layer config, you may consider removing this package from the package list or use the :toggle keyword instead of a `when' form. 
and 
org-cdlatex-mode: Cannot open load file: No such file or directory, cdlatex

Thanks a lot for your help!

**Comment by ekaschalk** [comment]
You need to define the `config/init-cdlatex`, `config/init-org-brain`, ... functions in the layer making a call to `use-package`, in addition to adding it to the `config-packages` variable, see `outshine`'s setup for example.

The warning is telling you that the layer isn't owning the package, and no other layer does, so it doesn't get installed.

**Comment by yubrshen** [comment]
Thanks for your help! Yes following your instruction now I added the following:
```
(defun config/init-cdlatex ()
  (use-package cdlatex
    :after auctex org
    :init
    (progn
      (load "~/programming/emacs-lisp/texmathp.el")
      (load "~/programming/emacs-lisp/org-cdlatex-try-tab/org-cdlatex-try-tab.el")
      ;; the command =C- SHIFT TAB= for trigger cdtalx abbrev expansion in org-mode
      ;; This is my private setup.

      ;; enable CDLaTex minor-mode for entering math (equations, or symbols)
      (add-hook 'org-mode-hook 'turn-on-org-cdlatex)
      )))
```
Now there is no more complaint against missing cdlatex. But I noticed that cdlatex needs texmathp.el, which is not a package. So I tried to directly load it in the init section, but it seems that it didn't work. I had  to manually load it to make it available. 

Another issue is that the last `add-hook` seemed didn't have the effect. I also had to manually enable the minor mode org-cdlatex-mode

Thanks again!

**Comment by yubrshen** [comment]
Actually, after I removed `auctex` in` :after `clause, it all worked as expected now. 
(Initially, I was hoping to install `auctex` in order to have `texmathp`, but it didn't work, and I solved the problem by just downloading a private copy of texmathp.el)
