### ISSUE TITLE
table outline on org mode

### ISSUE THREAD

**Issue by sigu** [ekaschalk/dotspacemacs#12]
When including a line below the row then the `+` signs no longer align with the respective rows, this is caused by the pretty fonts package (it displays fine when I disable the package)  but I am not sure of how to solve it.
![screenshot from 2018-03-04 13-24-42](https://user-images.githubusercontent.com/584211/36944584-e417c674-1fb0-11e8-804f-feab9232e126.png)

**Comment by sigu** [comment]
I disabled one of the ligature definitions then its now okay
`    ;; ("\\(--\\)"       #Xe111) ("\\(---\\)"         #Xe112)`

Is this the **best** solution?
![screenshot from 2018-03-04 13-35-39](https://user-images.githubusercontent.com/584211/36944592-04af13ce-1fb1-11e8-8ff2-06e1da121351.png)

**Comment by ekaschalk** [comment]
Yes this is the problem and solution. A more fancy regex would likely do the trick to stop composing when at a 4+ length string of dashes.
