### ISSUE TITLE
Error when start your config

### ISSUE THREAD

**Issue by danliustc** [ekaschalk/dotspacemacs#13]
In my country, melpa is not so stable, so i just want add a mirror site for melpa, where should i put it? Hope for your suggestion, thank you!

**Comment by danliustc** [comment]
Now, i just put it in your user-config() function, but i do think it's cool as your code...

**Comment by ekaschalk** [comment]
Spacemacs has settings for elpa.

Some people use a `site-lisp` directory where they download all their packages to and load from there.

Spacemacs has `dotspacemacs-elpa-subdirectory` in the `init.el` you can try out.

**Comment by danliustc** [comment]
En.....it works, thanks.
