### ISSUE TITLE
How to by-passing the aspect of using special fonts?

### ISSUE THREAD

**Issue by yubrshen** [ekaschalk/dotspacemacs#15]
This is not really a bug, but rather a question for my own situation. Sorry to bother you. 

In my office environment of Windows 7, I don't have administrator privileges, thus I can't install special ttf fonts. Thus the display aspect of your excellent package is not usable, causing very poor display with not legible icons. 

So I'd like to seek your advice on how I can disable or by-pass the display functionalities requiring special fonts. 

Thanks!

**Comment by ekaschalk** [comment]
I set all the unicode points that reference the ttf fonts in the display layer's `package.el`. So either specify points that don't require a ttf font or disable them entirely within that file, and that should be sufficient.

**Comment by yubrshen** [comment]
Thanks for the advice.
