### ISSUE TITLE
Help with pretty outlines

### ISSUE THREAD

**Issue by kepi** [ekaschalk/dotspacemacs#19]
Hello, I'm trying to use your `pretty-outlines` in outshine buffer and it is simply not working. There is no error message no matter if I load `pretty-outlines-add-bullets` with hook or manually, heading still looks same.

I even tried to load almost default spacemacs (develop) config so I can rule out some conflict with my configuration but result is the same.

Can you think about some simple way how to find what I'm doing wrong? I tried to warp my head around the code but I'm not up to the challenge with my current elisp level.

**Comment by ekaschalk** [comment]
I'm refactoring the display packages currently. Hopefully that might help your issue.

**Comment by ekaschalk** [comment]
Hi it took abit but pretty-outlines is redone and uses a different method than before. Hopefully it fixes your issues, feel free to reopen if it does not and I'll look closer.
