### ISSUE TITLE
outline-ivy.el

### ISSUE THREAD

**Issue by TLINDEN** [ekaschalk/dotspacemacs#2]
Hi,

no worries, I just don't know how to contact you otherwise. I wrote a very similar tool like your outline-ivy.el, but for IDO: [outshine-ido.el](https://github.com/TLINDEN/dot-emacs/blob/master/tvd-outshine-ido-jump.el). I already asked the current outshine maintainer to add it, but he declined. Now I discovered your work and I wonder if it might make sense to merge them into a library or something.

What do you think?

best,
Tom

**Comment by ekaschalk** [comment]
I'm open to that - what features do you envision for it?

Functioning for all of ivy/helm/ido would be important. Integrating more commands than jump like jump-and-narrow. Possibly some projectile or other way to search across many files are my thoughts.
