### ISSUE TITLE
pretty-outlines: missing a require

### ISSUE THREAD

**Issue by easbarba** [ekaschalk/dotspacemacs#22]
hi, 

There is a **require** missing at the top of **pretty-outlines.el**.  It's issuing a minor error: 

```variable void: incf``` 

`(require 'cl)`

:+1:

**Comment by ekaschalk** [comment]
Is CL not built-in to Emacs? Using Spacemacs I sometimes miss which packages are defaults.

**Comment by easbarba** [comment]
> Is CL not built-in to Emacs? Using Spacemacs I sometimes miss which packages are defaults.

It is. 

Cant say about Spacemacs, but non-spacemacs config will issue that error, if no (require 'cl) is called!

**Comment by ekaschalk** [comment]
Thanks for the heads up fixed.
