### ISSUE TITLE
C-c C-c broken for notes

### ISSUE THREAD

**Issue by commandodev** [ekaschalk/dotspacemacs#28]
I've raised an issue with spacemacs here https://github.com/syl20bnr/spacemacs/issues/11844 because my `C-c C-c` keybinding doesn't do anything in `*Org Note*` buffers. I suspected something to do with ivy or counsel as explained in the issue, but I think that was a red herring.

Just as a sanity check I switched back to vanilla spacemacs and the `C-c C-c` keybinding works. Do you have any problems saving a note (`, i n`, type something, `C-c C-c`) in org mode?

**Comment by commandodev** [comment]
I've done a bit of a binary search and it seems to be the outshine package that's causing a problem. If I comment this https://github.com/ekaschalk/.spacemacs.d/blob/master/layers/config/packages.el#L18.

If I comment this line note saving seems to be working

**Comment by commandodev** [comment]
OK - I think that's confirmed. I've put every thing back (including ivy) and just left that line uncommented and note saving still works. I think this https://github.com/syl20bnr/spacemacs/issues/11832 is related.

**Comment by commandodev** [comment]
Looks like there's an issue open on outshine for this too: https://github.com/alphapapa/outshine/issues/45

**Comment by ekaschalk** [comment]
The linked issue has been closed so I'll close this too.
