### ISSUE TITLE
Ligatures not displaying

### ISSUE THREAD

**Issue by sigu** [ekaschalk/dotspacemacs#3]
This is how typescript functions are showing in my emacs: take note of the symbol (bin) it shows for semicolons and the `fat arrow` becomes just a box 
```
OS: arch Linux
emacs: 25.2.1
spacemacs: 0.200.9
```

I have also installed the `Fira code` in my system and it works perfectly fine on my `Gedit`
![screenshot from 2017-07-23 18-18-39](https://user-images.githubusercontent.com/584211/28500631-42272a12-6fd4-11e7-9e04-6b19b6372693.png)

**Comment by ekaschalk** [comment]
Are all fira code ligatures not displaying? What are the names of the Fira fonts you have installed? I'm not sure if there is a standalone link to the ligatures anymore - the "Fira Code Symbol" font. If you don't have that installed, try just "Fira Code" in the pretty-fonts package.

Note that just setting the font to Fira Code will not have an impact on ligatures, it must be done by setting the range of unicode points to the font containing the ligatures.

**Comment by sigu** [comment]
They were displaying weird characters, I looked for the `Fira Font Symbol` and viola! it worked. Here is the link to the symbol font https://github.com/tonsky/FiraCode/files/412440/FiraCode-Regular-Symbol.zip
Thanks for the pointers

**Comment by sigu** [comment]
They were displaying weird characters, I looked for the `Fira Font Symbol` and viola! it worked. Here is the link to the symbol font https://github.com/tonsky/FiraCode/files/412440/FiraCode-Regular-Symbol.zip
Thanks for the pointers
