### ISSUE TITLE
error when start up "Symbol’s function definition is void: redo-spacemacs-bindings"

### ISSUE THREAD

**Issue by atreeyang** [ekaschalk/dotspacemacs#31]
Erro when start up the emacs, with emacs 26.3 spacemacs develop branch.

Auto-evilification could not remap these functions in map ‘mu4e-headers-mode-map’:
   - ‘mu4e-headers-query-prev’ originally mapped on ‘\’
Auto-evilification could not remap these functions in map ‘mu4e-headers-mode-map’:
   - ‘mu4e-headers-query-prev’ originally mapped on ‘\’
Package html2text is obsolete!
Spacemacs is ready.
(Spacemacs) Error in dotspacemacs/user-config: Symbol’s function definition is void: redo-spacemacs-bindings

[yas] Prepared just-in-time loading of snippets successfully.
Starting new Ispell process /usr/local/bin/ispell with default dictionary...

**Comment by ekaschalk** [comment]
Hm thought my guards were already sufficient.

Pushed a fix with some extra checks so /should/ be gone.

Thanks for the heads up.
