### ISSUE TITLE
Can not enable ligatures

### ISSUE THREAD

**Issue by Anton-Latukha** [ekaschalk/dotspacemacs#33]
Went through blog post http://www.modernemacs.com/post/prettify-mode/.

Hacked around, searched your code base. How to enable ligatures?
What does:
```elisp
;; To enable them, you need to add:

(pretty-fonts-set-kwds
'((pretty-fonts-fira-font prog-mode-hook org-mode-hook)))
```

Means. There is no `pretty-fonts-set-kwds` function, there is no `pretty-fonts-fira-font`. I can not decipher what these instructions are and where to apply them.

**Comment by Anton-Latukha** [comment]
Found and used:
https://github.com/ekaschalk/.spacemacs.d/blob/4f038ca89e8de9edfd9b3e14fa76c7c2343953d9/layers/display/packages.el#L194-L224

Seems to work. But block post, to proper, needs to be updated.

**Comment by ekaschalk** [comment]
I'm not touching this implementation of ligatures anymore, because Emacs's core now has proper/native support for them with harfbuzz integrated. When someone implements a lisp interface for it, we won't need hacky solutions like this. Can only hope that comes soon.
