### ISSUE TITLE
Extract outline-ivy

### ISSUE THREAD

**Issue by DamienCassou** [ekaschalk/dotspacemacs#4]
Hi,

I wanted to test outline-ivy but it is apparently bundled with the rest of your config. Could you please extract it to a separate package?

Thanks

**Comment by ekaschalk** [comment]
I'll eventually make the local packages git submodules for easy cloning.

For now it should be enough to save outline-ivy.el to your load path, require it, and bind `oi-jump` to whatever key you wish, I use `C-j`.

**Comment by DamienCassou** [comment]
I'm still interested in having outline-ivy in a dedicated package. That would allow me to get updates automatically.
