### ISSUE TITLE
How do I choose alternative to "operator mono"?

### ISSUE THREAD

**Issue by yubrshen** [ekaschalk/dotspacemacs#8]
I'm really interested in your approach of personal-layers for spacemacs customization. 

But I have a question of how to choose the alternative to "operator mono", based on the following statement:

"You won’t have the font operator mono installed so make sure to select your font of choice."

**Comment by ekaschalk** [comment]
`dotspacemacs-default-font` in `init.el`. It contains all the standard spacemacs configuration.

**Comment by yubrshen** [comment]
Thanks! 
It might save your time over the long run to state something like 'If "operator mono" fonts are available, one can customize init.el to use them."
